@baseUrl = http://localhost:5259
@movieId = 16
@actorId = 1

GET {{baseUrl}}/weatherforecast/
Accept: application/json

###
GET {{baseUrl}}/api/movies

###
GET {{baseUrl}}/api/movies/{{movieId}}

###
GET {{baseUrl}}/api/actors

###
GET {{baseUrl}}/api/actors/{{actorId}}

###
POST {{baseUrl}}/api/movies
Content-Type: application/json
{
   "title": "Project Hail Mary",
   "year": "2026",
   "genre": "Sci-fi",
   "duration": "156",
   "actorIds": [2, 4]
}

### Create Actor
POST {{baseUrl}}/api/actors
Content-Type: application/json
{
   "name": "James Ortiz",
   "YearOfBirth": "1984"
}

### Add Actor to Movie
POST {{baseUrl}}/api/actors/{{movieId}}/actors
Content-Type: application/json
[5] // IDs of actors to add

### {
###   "title": "Rogue One",
###   "year": "2016",
###   "genre": "Action",
###   "duration": "134"
### }

### Update movie (full update with PUT)
PUT {{baseUrl}}/api/movies/{{movieId}}
Content-Type: application/json

{
    "Title": "Pirates of the Caribbean",
    "Year": 2003,
    "Genre": "Adventure",
    "Duration": 143
}

### Partially update movie (PATCH with JSON Patch - Replace operation)
PATCH {{baseUrl}}/api/movies/{{movieId}}
Content-Type: application/json-patch+json
[
  {
    "op": "replace",
    "path": "/title",
    "value": "The curse of the black pearl"
  }
]

### Delete movie
DELETE {{baseUrl}}/api/movies/{{movieId}}

### Delete actor
DELETE {{baseUrl}}/api/actors/{{movieId}}