@baseUrl = http://localhost:5259
@ID = 2

GET {{baseUrl}}/weatherforecast/
Accept: application/json

###
GET {{baseUrl}}/api/movies

###
GET {{baseUrl}}/api/movies/{{id}}

###
GET {{baseUrl}}/api/actors

###
POST {{baseUrl}}/api/movies
Content-Type: application/json
{
   "title": "Project Hail Mary",
   "year": "2026",
   "genre": "Sci-fi",
   "duration": "156"
}

###
POST {{baseUrl}}/api/actors
Content-Type: application/json
{
   "name": "Johnny Depp",
   "YearOfBirth": "1963"
}

###
POST {{baseUrl}}/api/actors/{{id}}
Content-Type: application/json
{
   "name": "Ryan Gosling",
   "YearOfBirth": "1992"
}

### {
###   "title": "Your Name",
###   "year": "2016",
###   "genre": "Romance",
###   "duration": "107"
### }
### {
###   "title": "Rogue One",
###   "year": "2016",
###   "genre": "Action",
###   "duration": "134"
### }

### Update movie (full update with PUT)
PUT {{baseUrl}}/api/movies/{{id}}
Content-Type: application/json

{
    "Title": "Pirates of the Caribbean",
    "Year": 2003,
    "Genre": "Adventure",
    "Duration": 143
}

### Partially update movie (PATCH with JSON Patch - Replace operation)
PATCH {{baseUrl}}/api/movies/{{id}}
Content-Type: application/json-patch+json
[
  {
    "op": "replace",
    "path": "/title",
    "value": "The curse of the black pearl"
  }
]

### Delete movie
DELETE {{baseUrl}}/api/movies/{{id}}

### Delete actor
DELETE {{baseUrl}}/api/actors/{{id}}