@baseUrl = http://localhost:5259
@movieId = 4
@actorId = 1010
@reviewId = 1
@genreId = 6

### Get all movies
GET {{baseUrl}}/api/movies

### Get all movies filtered
GET {{baseUrl}}/api/movies?name=Dunkirk
Accept: application/json

### Get all movies searched
GET {{baseUrl}}/api/movies?searchQuery=Sci-fi
Accept: application/json

### Get movie by Id
GET {{baseUrl}}/api/movies/{{movieId}}

### Get movie by Id + details
GET {{baseUrl}}/api/movies/{{movieId}}/details

### Get all actors
GET {{baseUrl}}/api/actors

### Get all actors searched
GET {{baseUrl}}/api/actors?searchQuery=Diego

### Get actor by Id
GET {{baseUrl}}/api/actors/{{actorId}}

### Get all reviews
GET {{baseUrl}}/api/reviews

### Get review by Id
GET {{baseUrl}}/api/reviews/{{reviewId}}

### Get all genres
GET {{baseUrl}}/api/genres

### Create genre
POST {{baseUrl}}/api/genres
Content-Type: application/json

{
  "name": "Thriller",
  "description": "Suspense and intrigue"
}

### Create setting
POST {{baseUrl}}/api/Settings
Content-Type: application/json

{
  "name": "Contemporary",
  "description": "In this day and age"
}

### Create movie
POST {{baseUrl}}/api/movies
Content-Type: application/json

{
  "Title": "Rogue One",
  "Year": 2016,
  "GenreId": 2,
  "SettingId": 2,
  "Duration": 134
}

### Create Actor
POST {{baseUrl}}/api/actors
Content-Type: application/json

{
   "name": "Genevieve O'Reilly",
   "YearOfBirth": "1977"
}

### Create actor in movie
POST {{baseUrl}}/api/movies/{{movieId}}/actor
Content-Type: application/json

{
   "name": "Alan Tudyk",
   "YearOfBirth": "1971"
}

### Create movieDetails
POST {{baseUrl}}/api/movies/{{movieId}}/details
Content-Type: application/json

{
  "synopsis": "People leave a beach dramatically",
  "language": "English",
  "budget": 100
}

### Create Review
POST {{baseUrl}}/api/reviews
Content-Type: application/json

{
   "ReviewerName": "Acasez",
   "Comment": "The Best Star Wars Movie",
   "Rating": 10,
   "MovieId": 10
}

### Add Actor to Movie
POST {{baseUrl}}/api/actors/{{movieId}}/actors
Content-Type: application/json
[1007] // IDs of actors to add

### Update movie (full update with PUT)
PUT {{baseUrl}}/api/movies/{{movieId}}
Content-Type: application/json

{
    "Title": "Dunkirk",
    "Year": 2017,
    "GenreId": 3,
    "Duration": 106
}

### Partially update movie (PATCH with JSON Patch - Replace operation)
PATCH {{baseUrl}}/api/movies/{{movieId}}
Content-Type: application/json-patch+json
[
  {
    "op": "replace",
    "path": "/title",
    "value": "The curse of the black pearl"
  }
]

### Delete movie
DELETE {{baseUrl}}/api/movies/{{movieId}}

### Delete actor
DELETE {{baseUrl}}/api/actors/{{actorId}}

### Delete genre
DELETE {{baseUrl}}/api/genres/{{genreId}}

### Delete movieDetails
DELETE {{baseUrl}}/api/movies/details/2